vich_uploader:
    db_driver: orm

    mappings:
        images_upload:
            uri_prefix: '/%env(WEB_IMAGES_UPLOAD)%'
            upload_destination: '%kernel.project_dir%/%env(SYS_IMAGES_UPLOAD)%'
            delete_on_update: false
            delete_on_remove: false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        files_upload:
            uri_prefix: '/%env(WEB_FILES_UPLOAD)%'
            upload_destination: '%kernel.project_dir%/%env(SYS_FILES_UPLOAD)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
